project "smf"
do
	kind "StaticLib"
	language "C"

	local useconfig = (string.lower(tostring(_OPTIONS["use-config"])) == "yes")
	local useglib = (string.lower(tostring(_OPTIONS["use-glib"])) == "yes")
	
	local version = "1.3.1"
	includedirs {
		"../../src",
	}
	
	if useconfig then
		defines { "HAVE_CONFIG_H" }
		-- location of the config.h generated by premake action "config"
		includedirs { "%{cfg.location}/%{cfg.shortname}/include" }
	else
		for k, v in pairs ({
			PACKAGE_VERSION = '"'..version..'"',
			VERSION = '"'..version..'"'
		}) do
			defines (k .. "=" .. v)
		end
	end
	
	files { 
		"../../src/smf.h",
		"../../src/smf.c",
		"../../src/smf_decode.c",
		"../../src/smf_load.c",
		"../../src/smf_tempo.c",
		"../../src/smf_private.h",
		"../../src/smf_save.c"
	}
	
	if not useglib
	then
		defines { "SMF_GLIB_COMPILATION" }
		sysincludedirs { "../../smfglib/include" }
		files { "../../smfglib/src/**.c" }
	end
	
end
