project "smfsh"
do
	kind "StaticLib"
	language "C"

	local useconfig = (tostring(string.lower(_OPTIONS["use-config"])) == "yes")
	local useglib = (tostring(string.lower(_OPTIONS["use-glib"])) == "yes")
	
	includedirs {
		"../../src",
	}
	
	if useconfig then
		defines { "HAVE_CONFIG_H" }
		-- location of the config.h generated by premake action "config"
		includedirs { "%{cfg.location}/%{cfg.shortname}/include" }
	end
	
	files { 
		"../../src/smfsh.c"
	}

	links { "smf" }
	
	if not useglib
	then
		sysincludedirs { "../../smfglib/include" }
	end	
	
end
